---
title: "day2_deq"
author: "Jack Wilburn"
date: "2/16/2020"
output: html_document
---

# Day two

## Importing and writing data

## Importing data

``` {r}
# csv
iris <- read.csv("datasets/iris.csv")
iris2 <- read.csv2("datasets/iris.csv") # deals with semicolon delimiters

install.packages("tidyverse") # or just readr
library(readr) # The preferred package for importing common datatypes (csv, text, log, table, RDS, etc.)
iris3 <- read_csv("datasets/iris.csv")
iris4 <- read_csv("datasets/iris.csv", col_types = "ccccf") # show them and ask them what this means, gentle push to help files
# Can also be achieved after the fact but it might cause data loss (if it assumes a logical and it's character for example)

iris5 <- read_csv("datasets/iris.csv", skip=110)
iris6 <- read_csv("datasets/iris.csv", n_max = 10)

iris7<- read_csv("datasets/iris.csv", progress = TRUE) # Why didn't this work? Have them read the documentation

# netCDF
install.packages("ncdf4")
library(ncdf4)
nc <- nc_open("datasets/ncdfexample.nc")
print(nc)
attributes(nc)
attributes(nc$var)
attributes(nc$var)$names
ncvar_get(nc, attributes(nc$var)$names[1])

nc_lat <- ncvar_get(nc, "lat_bnds")[1, ]
nc_lon <- ncvar_get(nc, "lon_bnds")[1, ]
area <- ncvar_get(nc, "area")

dim(area)

dimnames(area) <- list(nc_lon, nc_lat)
View(area[1:10, 1:10])

# xlsx
install.packages("readxl")
library(readxl)

df <- read_excel()
df <- readxl_example("datasets.xls")
excel_sheets(df)
df <- read_excel(df, sheet = "chickwts")
# Can't re-run just the sheet command, has to be the whole thing again 


# txt files
news <- read_lines("datasets/news.txt") # has similar options to read_csv since it's pretty much doing the same thing

# DATABASES (SQL over to the right) (do they have drivers?)
library(odbc)
con <- odbc::dbConnect(drv = odbc::odbc(), driver = "ODBC Driver 17 for SQL Server", 
    server = "x.x.x.x", uid = "me", pwd = "123", 
    database = "R4W_003")

# Exporting data
write_csv(iris5, "datasets/iris_short.csv")
write_ # explore options
# Each package to handle data comes with imports and exports (so depends on file type, etc)

# write xlsx as csv unless it's not possible, then use the package xlsx
dimension <- ncdim_def("area_dim", "m^2", as.double(area))
nc_create("datasets/example.nc", dimension)
variable <- ncvar_def("area", "m^2", list(dimension), prec="single")
nc_create("datasets/example.nc", variable) # Check file size

variable2 <- ncvar_def("area2", "m^2", list(dimension), prec="single")
example <- nc_open("datasets/example.nc", write = TRUE)
ncvar_add(example, variable2)
nc_close(example) # Check file size again

# You can do something similar with the put command to update a variable instead of just creating it
```


## Data visualization


```{r}
library(ggplot2)

diamonds

# Histograms/KDE (1 numeric)
ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 2000) 

ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 2000, color = "#99ff66") 

ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 2000, fill = "#99ff66")

ggplot(diamonds, aes(price)) +
  geom_density(binwidth = 2000, fill = "#99ff66") + 
  scale_x_continuous(labels = scales::dollar_format())

options(scipen = 1000000)

ggplot(diamonds, aes(price)) +
  geom_density(binwidth = 2000, fill = "#99ff66") + 
  scale_x_continuous(labels = scales::dollar_format())


# Bar charts (1 categorical)
ggplot(diamonds, aes(cut)) +
  geom_bar()

diamonds$cut <- factor(diamonds$cut, levels = c("Ideal", "Premium", "Very Good", "Good", "Fair"))

ggplot(diamonds, aes(cut)) +
  geom_bar()

diamonds$cut <- factor(diamonds$cut, levels = c("Very Good", "Ideal", "Fair", "Premium",  "Good"))

ggplot(diamonds, aes(cut)) +
  geom_bar()

sort(table(diamonds$cut))
sort(table(diamonds$cut), decreasing = TRUE)
names(sort(table(diamonds$cut), decreasing = TRUE))

diamonds <- within(
  diamonds, 
  cut <- factor(
    cut, 
    levels = names(sort(table(cut), decreasing = TRUE))
  )
)

ggplot(diamonds, aes(cut)) +
  geom_bar()


# Facetted histograms and side by side boxplot (1 numeric, 1 categorical)
ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 2000) + 
  facet_wrap( ~ cut)

ggplot(diamonds, aes(price)) +
  geom_histogram(binwidth = 2000) + 
  facet_wrap( ~ cut, ncol = 1)

ggplot(diamonds, aes(price, fill = cut)) +
  geom_histogram(binwidth = 2000)

ggplot(diamonds, aes(price, fill = cut)) +
  geom_histogram(binwidth = 2000) + 
  facet_wrap( ~ cut, ncol = 1)

ggplot(diamonds, aes(cut, price)) +
  geom_boxplot()

ggplot(diamonds, aes(cut, price)) +
  geom_boxplot() + 
  coord_flip()

ggplot(diamonds, aes(cut, price, fill = cut)) +
  geom_boxplot() + 
  coord_flip()

# Scatter plots (2 numeric, a couple categorical)
ggplot(diamonds, aes(carat, price)) +
  geom_point() 

ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth(method = lm)

ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth(method = lm) +
  scale_x_log10()

ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth(method = lm) +
  scale_y_log10()

ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  geom_smooth(method = lm) +
  scale_x_log10() +
  scale_y_log10()

ggplot(diamonds, aes(log10(carat), log10(price))) +
  geom_point() +
  geom_smooth(method = lm)

ggplot(diamonds, aes(log10(carat), log10(price))) +
  geom_point(fill = cut) # breaks

ggplot(diamonds, aes(log10(carat), log10(price))) +
  geom_point(aes(color = cut))

ggplot(diamonds, aes(log10(carat), log10(price), color = cut)) +
  geom_point()

# Side by side bar charts (2 categorical)
ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar()

ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge")

ggplot(diamonds, aes(x = cut, y = ..count.., fill = color)) + 
  geom_bar(position = "dodge")

ggplot(diamonds, aes(x = cut, y = ..count../sum(..count..), fill = color)) + 
  geom_bar(position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format())

ggplot(diamonds, aes(x = cut)) + 
  geom_bar(aes(y = ..prop.., group = 1), position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format()) + 
  facet_wrap( ~ color)

diamonds <- count(answer, gender) %>% 
mutate(freq = n/if_else(gender == 'Male', male.total, female.total))


# Theme-ing the plots
ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge") +
  labs(
    title = "Diamond Count By Cut And By Color",
    x = "Cut",
    y = "Count",
    fill = "Diamond color"
  )

ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge") +
  labs(
    title = "Diamond Count By Cut And By Color",
    x = "Cut",
    y = "Count",
    fill = "Diamond\ncolor"
  )

?theme

ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge") +
  labs(
    title = "Diamond Count By Cut And By Color",
    x = "Cut",
    y = "Count",
    fill = "Diamond\ncolor"
  ) +
  theme_minimal()

ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge") +
  labs(
    title = "Diamond Count By Cut And By Color",
    x = "Cut",
    y = "Count",
    fill = "Diamond\ncolor"
  ) +
  theme(
    plot.title = element_text(size = 24)
  )

ggplot(diamonds, aes(x = cut, fill = color)) + 
  geom_bar(position = "dodge") +
  labs(
    title = "Diamond Count By Cut And By Color",
    x = "Cut",
    y = "Count",
    fill = "Diamond\ncolor"
  ) +
  theme(
    plot.title = element_text(size = 18),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "#AAAAAA")
  )

ggplot(diamonds, aes(cut)) +
  geom_bar(fill = "#0080b7", color = "white") +
  geom_text(size = 6, stat = 'count', aes(label = scales::percent(..count../nrow(diamonds), accuracy = 0.1), vjust = -0.5))

# Fully complete examples
custom_theme <- theme(
    plot.title = element_text(size = 18),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_line(color = "#AAAAAA")
  )

ggplot(diamonds, aes(price)) +
  geom_density(binwidth = 2000, fill = "#0080b7", color = "white") + 
  scale_x_continuous(labels = scales::dollar_format()) +
  labs(
    title = "Diamond Price",
    x = "Price",
    y = "Density"
  ) + 
  custom_theme

ggplot(diamonds, aes(cut)) +
  geom_bar(fill = "#0080b7", color = "white") +
  labs(
    title = "Diamond Quality",
    x = "Quality",
    y = "Count"
  ) + 
  custom_theme + 
  geom_text(size = 4, stat = 'count', aes(label = scales::percent(..count../nrow(diamonds), accuracy = 0.1), vjust = -0.1))

ggplot(diamonds, aes(price, fill = cut)) +
  geom_histogram(binwidth = 2000) + 
  facet_wrap( ~ cut, ncol = 1) +
  labs(
    title = "Diamond Price by Cut Type",
    x = "Price",
    y = "Count"
  ) + 
  custom_theme

ggplot(diamonds, aes(cut, price, fill = cut)) +
  geom_boxplot() + 
  coord_flip() +
  labs(
    title = "Diamond Quality",
    x = "Cut",
    y = "Price"
  ) + 
  custom_theme

ggplot(diamonds, aes(log10(carat), log10(price))) +
  geom_point(aes(color = cut)) + 
  labs(
    title = "Diamond Price vs. Size",
    x = "Log diamond size (carats)",
    y = "Log diamond price"
  ) + 
  custom_theme + 
  theme(panel.grid.major = element_line(color = "#AAAAAA"))







# Pie Chart
ggplot(diamonds,aes(x = "", fill=clarity)) + 
  geom_bar(width =1) + 
  coord_polar(theta="y")

# Coxcomb Chart
ggplot(diamonds,aes(x = clarity, fill=clarity)) + 
  geom_bar(width =1) + 
  coord_polar (theta="x")


```



```{r}
x = "hello" + " world"
print(x)
```



```{python}
x = "hello" + " world"
print(x)
```

The value of `x` in the Python session is `r py$x`.
It is not the same `x` as the one in R.


















